# DummyRegressor

## Importação de bibliotecas

In [ ]:
import pandas as pd
import numpy as np
from sklearn.dummy import DummyRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

## Importação de dataset

In [2]:
data = pd.read_csv("/content/carne-brasileira-exportada.csv", encoding='utf-8', sep=',')
data.head()

,ano,trimestre,tipo_carne,producao_cabecas_anual_mi,abate_cabecas,peso_carcaca_ton,exportacao_usd,media_cambio_usdbrl,custo_milho_rs,custo_soja_rs,preco_medio_ton_usd
0,2014,1,bovino,212.34,8.366,1.951,1.345,2.34,22.57,62.01,4.403
1,2014,2,bovino,212.34,8.516,2.006,1.384,2.22,23.59,61.42,4.729
2,2014,3,bovino,212.34,8.456,2.036,1.547,2.28,19.97,56.50,4.874
3,2014,4,bovino,212.34,8.525,2.058,1.519,2.59,21.46,56.73,4.858
4,2014,1,suino,37.93,8.686,0.747,0.260,2.34,22.57,62.01,2.811

## Separação de dataset por carne

In [3]:
bovino = data[data['tipo_carne'] == 'bovino'].copy()
bovino.head()

,ano,trimestre,tipo_carne,producao_cabecas_anual_mi,abate_cabecas,peso_carcaca_ton,exportacao_usd,media_cambio_usdbrl,custo_milho_rs,custo_soja_rs,preco_medio_ton_usd
0,2014,1,bovino,212.34,8.366,1.951,1.345,2.34,22.57,62.01,4.403
1,2014,2,bovino,212.34,8.516,2.006,1.384,2.22,23.59,61.42,4.729
2,2014,3,bovino,212.34,8.456,2.036,1.547,2.28,19.97,56.50,4.874
3,2014,4,bovino,212.34,8.525,2.058,1.519,2.59,21.46,56.73,4.858
12,2015,1,bovino,215.20,7.737,1.836,0.993,2.87,22.95,60.01,4.279

In [4]:
suino = data[data['tipo_carne'] == 'suino'].copy()
suino.head()

,ano,trimestre,tipo_carne,producao_cabecas_anual_mi,abate_cabecas,peso_carcaca_ton,exportacao_usd,media_cambio_usdbrl,custo_milho_rs,custo_soja_rs,preco_medio_ton_usd
4,2014,1,suino,37.93,8.686,0.747,0.260,2.34,22.57,62.01,2.811
5,2014,2,suino,37.93,9.151,0.797,0.375,2.22,23.59,61.42,3.471
6,2014,3,suino,37.93,9.640,0.833,0.399,2.28,19.97,56.50,3.774
7,2014,4,suino,37.93,9.494,0.802,0.410,2.59,21.46,56.73,3.674
16,2015,1,suino,40.33,9.170,0.794,0.197,2.87,22.95,60.01,2.589

In [5]:
frango = data[data['tipo_carne'] == 'frango'].copy()
frango.head()

,ano,trimestre,tipo_carne,producao_cabecas_anual_mi,abate_cabecas,peso_carcaca_ton,exportacao_usd,media_cambio_usdbrl,custo_milho_rs,custo_soja_rs,preco_medio_ton_usd
8,2014,1,frango,1331.0,1.395,3.192,1.470,2.34,22.57,62.01,1.779
9,2014,2,frango,1331.0,1.378,3.179,1.764,2.22,23.59,61.42,1.932
10,2014,3,frango,1331.0,1.418,3.249,1.881,2.28,19.97,56.50,1.939
11,2014,4,frango,1331.0,1.406,3.176,1.776,2.59,21.46,56.73,1.891
20,2015,1,frango,1330.0,1.382,3.164,1.354,2.87,22.95,60.01,1.627

### Ordenação temporal

In [6]:
bovino = bovino.sort_values(by=['ano', 'trimestre']).reset_index(drop=True)

In [7]:
suino = suino.sort_values(by=['ano', 'trimestre']).reset_index(drop=True)

In [8]:
frango = frango.sort_values(by=['ano', 'trimestre']).reset_index(drop=True)

## Baseline para bovino

### Definição de variáveis

In [9]:
y = bovino['exportacao_usd']

### Separação temporal

In [10]:
split = int(len(bovino) * 0.8)

y_train = y.iloc[:split]
y_test = y.iloc[split:]

### DummyRegressor

In [11]:
X_train = np.zeros((len(y_train), 1))
X_test = np.zeros((len(y_test), 1))

model = DummyRegressor(strategy="mean")
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

### Avaliação

In [12]:
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(mae, rmse)

1.0301079365079366 1.103257238225132

## Baseline para suíno

### Definição de variáveis

In [13]:
y = suino['exportacao_usd']

### Separação temporal

In [14]:
split = int(len(suino) * 0.8)

y_train = y.iloc[:split]
y_test = y.iloc[split:]

### DummyRegressor

In [15]:
X_train = np.zeros((len(y_train), 1))
X_test = np.zeros((len(y_test), 1))

model = DummyRegressor(strategy="mean")
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

### Avaliação

In [16]:
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(mae, rmse)

0.2733523809523809 0.2861766582513171

## Baseline para frango

### Definição de variáveis

In [17]:
y = frango['exportacao_usd']

### Separação temporal

In [18]:
split = int(len(frango) * 0.8)

y_train = y.iloc[:split]
y_test = y.iloc[split:]

### DummyRegressor

In [19]:
X_train = np.zeros((len(y_train), 1))
X_test = np.zeros((len(y_test), 1))

model = DummyRegressor(strategy="mean")
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

### Avaliação

In [20]:
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(mae, rmse)

0.5861111111111114 0.6070510686919184